version: "3.8"
services:
  app:
    container_name: app-container
    build:
      context: .
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    container_name: nginx-container
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge